language: r
sudo: required
os: linux 
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - sudo ldconfig

jobs:
  include:
  - r: devel
  - r: release
    cache:
      - packages
  - r: oldrel
    cache:
      - packages
  - r: release
    os: osx
    osx_image: xcode10.1
    before_install:
    - sudo tlmgr install inconsolata
    - sw_vers
    cache:
      - packages
      
warnings_are_errors: true

r_packages:
  - lwgeom
  - SpatialPosition
  - knitr
  - rmarkdown
  - tinytest
  - covr
  - rgdal
  
after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'